port: 6010
hr_source_dir: "data-dir/mip360/360_v2"
lr_source_dir: "data-dir/mip360/360_v2_lr"
vsr_save_dir: "data-dir/mip360/360_v2_vsr"
video_save_path: Null
spynet_path: "vsr/psrt/experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth"
vsr_model_path: "vsr/psrt/experiments/pretrained_models/PSRT_Vimeo.pth"
vsr_model: psrt
downscale_factor: 8
upscale_factor: 4
subpixel: "bicubic"
white_background: false
als : true
num_images_in_sequence: 8
similarity: 'pose'
thres_values: [30, 50]
lambda_tex: 0.40 
